feat: Update and `main.py` refactoring
viur-framework/viur-base pull request #128
Opened 2024-05-14 12:29 UTC by phorward

- Updates
  - Python 3.12
  - viur-core==3.6.5
  - viur-cli==2.0.1
- `main.py`
  - ProjectConf 
  - Updated conf-variables
  - Preprocessor examples
    - Domain enforcement
    - Maintenance mode
    - VueJS local development

2024-05-15 18:45 UTC, sveneberth requested changes
Please update the core

2024-05-15 18:45 UTC, sveneberth commented on Pipfile
> +viur-core = "==3.6.5"
```suggestion
viur-core = "~=3.6.6"
```

2024-05-15 18:45 UTC, sveneberth commented on Pipfile
> +viur-cli = "==2.0.1"
```suggestion
viur-cli = "~=2.0.1"
```

2024-05-21 12:01 UTC, sveneberth requested changes

2024-05-21 12:01 UTC, sveneberth commented on project.json
> +        "application_name": "{{app_id}}-dev",
```suggestion
        "application_name": "{{app_id}}",
```

2024-05-21 13:40 UTC, Grashalmbeisser approved these changes

2024-05-21 18:29 UTC, sveneberth approved these changes

2024-05-21 18:30 UTC, merged