Added CLOUD_LOGGING_ONLY Flag for custom Gcloudserviceaccount Support
viur-framework/viur-base pull request #129
Opened 2024-06-25 08:11 UTC by Grashalmbeisser

2024-07-05 11:18 UTC, phorward approved these changes

2024-07-09 12:30 UTC, sveneberth reviewed
Hey, The ignite repo has been renamed for a while and the spelling of the google products wasnt correct. Beside this please make the branch mergeable, it has currently conflicts.

2024-07-09 12:30 UTC, sveneberth commented on cloudbuild.yaml
> +#     git config -f .gitmodules submodule.sources/less/ignite.url https://github.com/viur-framework/ignite.git
```suggestion
#     git config -f .gitmodules submodule.sources/less/ignite.url https://github.com/viur-framework/viur-ignite.git
```

2024-07-09 12:30 UTC, sveneberth commented on cloudbuild.yaml
> +        git config -f .gitmodules submodule.sources/less/ignite.url https://github.com/viur-framework/ignite.git
```suggestion
        git config -f .gitmodules submodule.sources/less/ignite.url https://github.com/viur-framework/viur-ignite.git
```

2024-07-09 12:30 UTC, sveneberth commented on cloudbuild.yaml
> +# allow AppEngine Deployment
```suggestion
# activate App Engine Admin API
# https://console.developers.google.com/apis/api/appengine.googleapis.com/overview
#
# allow App Engine Deployment
```

2024-07-23 19:58 UTC, sveneberth requested changes
@Grashalmbeisser  Please resolve the merge conflict

2024-07-26 16:02 UTC, sveneberth approved these changes

2024-07-26 16:04 UTC, merged