fix: `renderEditForm()` should display errors
viur-framework/viur-base pull request #135
Opened 2024-09-06 13:54 UTC by phorward

2024-09-10 11:17 UTC, sveneberth requested changes

2024-09-10 11:17 UTC, sveneberth commented on deploy/html/editform/editform_row.html
> +            <span>{{ boneErrors[0].errorMessage if boneErrors and (boneErrors[0].severity.value == 3 or boneParams.required) }}</span>
Can we loop this, to show all messages?
```suggestion
            <span>
                {% for error in boneErrors -%}
                    {{ error.errorMessage if (error.severity.value == 3 or boneParams.required) }}
                    {%- if not loop.last %}<br>{% endif -%}
                {%- endfor %}
            </span>
```

2024-09-27 12:37 UTC, phorward commented on deploy/html/editform/editform_row.html
> +                    <span>{{ error.errorMessage }}</span>
```suggestion
                    <span class="ignt-input-error">{{ error.errorMessage }}</span>
```

2024-09-27 18:35 UTC, sveneberth approved these changes

2024-09-27 18:35 UTC, merged