Default behaviour when non-existent pages are requested
viur-framework/viur-base pull request #25
Opened 2020-10-30 15:22 UTC by xnopasaranx

Now throwing a 404 error when a path is requested that does not exist. Hopefully preventing annoying bots from bruteforcing.

2020-11-06 19:45 UTC, sveneberth requested changes

2020-11-06 19:45 UTC, sveneberth commented on deploy/modules/index.py
> +		if len(args) >= 1:
I think we can check the kwargs as well.
```suggestion
		if args or kwargs:
```

2020-12-16 13:15 UTC, phorward approved these changes

2020-12-16 16:32 UTC, sveneberth approved these changes

2020-12-16 16:33 UTC, merged